#!/bin/bash
echo "Enabling Mail bundles..."
defaults write com.apple.mail EnableBundles -bool true || exit 1
defaults write com.apple.mail BundleCompatibilityVersion 4 || exit 1

echo "Starting Mail..."
osascript -e "tell application \"Mail\"
activate
end tell"
